import { Router } from "express";
import { requireAuth,requireRole } from "../middleware/auth.middleware.js";
import { createVinRequest,decodeVinRequest,listClientVinRequests,getClientVinRequest,listManagerVinRequests,getVinSummary,updateVinRequest,addVinRecommendation,removeVinRecommendation,listSupportedVinBrands,listAdminVinBrands,addAdminVinBrand,toggleAdminVinBrand } from "../controllers/vin-request.controller.js";
export const publicVinBrandRouter=Router();publicVinBrandRouter.get('/',listSupportedVinBrands);
export const adminVinBrandRouter=Router();adminVinBrandRouter.use(requireAuth,requireRole('ADMIN'));adminVinBrandRouter.get('/',listAdminVinBrands);adminVinBrandRouter.post('/',addAdminVinBrand);adminVinBrandRouter.patch('/:brandId',toggleAdminVinBrand);
export const clientVinRequestRouter=Router();
clientVinRequestRouter.use(requireAuth);
clientVinRequestRouter.get('/',listClientVinRequests);
clientVinRequestRouter.post('/decode',decodeVinRequest);
clientVinRequestRouter.post('/',createVinRequest);
clientVinRequestRouter.get('/:requestId',getClientVinRequest);
export const managerVinRequestRouter=Router();
managerVinRequestRouter.use(requireAuth,requireRole('ADMIN','MANAGER'));
managerVinRequestRouter.get('/',listManagerVinRequests);
managerVinRequestRouter.get('/summary',getVinSummary);
managerVinRequestRouter.patch('/:requestId',updateVinRequest);
managerVinRequestRouter.post('/:requestId/recommendations',addVinRecommendation);
managerVinRequestRouter.delete('/:requestId/recommendations/:recommendationId',removeVinRecommendation);
