import { Router } from "express";
import { requireAuth,requireRole } from "../middleware/auth.middleware.js";
import { createVinRequest,decodeVinRequest,listClientVinRequests,getClientVinRequest,getVinPhoneVerification,addClientVinMessage,dismissClientVinRecommendation,listManagerVinRequests,getVinSummary,setVinClientBlock,updateVinRequest,addVinRecommendation,removeVinRecommendation,getVinSettings,updateVinSettings,listSupportedVinBrands,listAdminVinBrands,addAdminVinBrand,toggleAdminVinBrand } from "../controllers/vin-request.controller.js";
export const publicVinBrandRouter=Router();publicVinBrandRouter.get('/',listSupportedVinBrands);
export const adminVinBrandRouter=Router();adminVinBrandRouter.use(requireAuth,requireRole('ADMIN'));adminVinBrandRouter.get('/',listAdminVinBrands);adminVinBrandRouter.post('/',addAdminVinBrand);adminVinBrandRouter.patch('/:brandId',toggleAdminVinBrand);
export const clientVinRequestRouter=Router();
clientVinRequestRouter.use(requireAuth);
clientVinRequestRouter.get('/',listClientVinRequests);
clientVinRequestRouter.get('/phone-verification',getVinPhoneVerification);
clientVinRequestRouter.post('/decode',decodeVinRequest);
clientVinRequestRouter.post('/',createVinRequest);
clientVinRequestRouter.post('/:requestId/messages',addClientVinMessage);
clientVinRequestRouter.patch('/:requestId/recommendations/:recommendationId/dismiss',dismissClientVinRecommendation);
clientVinRequestRouter.get('/:requestId',getClientVinRequest);
export const managerVinRequestRouter=Router();
managerVinRequestRouter.use(requireAuth,requireRole('ADMIN','MANAGER'));
managerVinRequestRouter.get('/',listManagerVinRequests);
managerVinRequestRouter.get('/summary',getVinSummary);
managerVinRequestRouter.patch('/clients/:userId/block',setVinClientBlock);
managerVinRequestRouter.patch('/:requestId',updateVinRequest);
managerVinRequestRouter.post('/:requestId/recommendations',addVinRecommendation);
managerVinRequestRouter.delete('/:requestId/recommendations/:recommendationId',removeVinRecommendation);
export const adminVinSettingsRouter=Router();
adminVinSettingsRouter.use(requireAuth,requireRole('ADMIN'));
adminVinSettingsRouter.get('/',getVinSettings);
adminVinSettingsRouter.patch('/',updateVinSettings);
