BEGIN;


ALTER TABLE import_rows

ADD COLUMN IF NOT EXISTS old_price NUMERIC(12,2),

ADD COLUMN IF NOT EXISTS new_price NUMERIC(12,2),

ADD COLUMN IF NOT EXISTS change_percent NUMERIC(8,2),


ADD COLUMN IF NOT EXISTS old_quantity NUMERIC(10,2),

ADD COLUMN IF NOT EXISTS new_quantity NUMERIC(10,2),

ADD COLUMN IF NOT EXISTS quantity_change NUMERIC(10,2);



COMMIT;